### ISSUE TITLE
feature req: shouldReplace to return new id

### ISSUE THREAD

**Issue by privatenumber** [MarshallCB/rollup-plugin-skypin#1]
I'm looking to use this plugin with a `skypack:` prefix on bare specifiers:

```js
import pDebounce from 'skypack:p-debounce';
import ky from 'ky'; // Doesn't use Skypack
```

The `shouldReplace` option lets me specify which specifiers should use Skypack, but doesn't let me strip the `skypack:` prefix.

Can the return value of `shouldReplace` be used as the new id? Happy to open a PR.

**Comment by vimbrandt** [comment]
I like this idea!

I just updated the package (1.1.0) to allow for this, let me know if you run into any issues!

Now you should be able to do something like:

```js
skypin({
  shouldReplace(id){
    if(id.startsWith('skypack:')){
      return id.replace('skypack:', '')
    }
  }
})
```

I'm going to make similar package+plugin in the near future that supports more module CDN's (unpkg, jsdeliver, esm.sh). If you have any ideas / use cases, let me know and I'll keep them in mind!

**Comment by privatenumber** [comment]
Awesome, thank you @MarshallCB !
